#ifndef __MDM_OBJECTID_H__
#define __MDM_OBJECTID_H__


/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


/*!\file mdm_objectid.h 
 * \brief Automatically generated header file mdm_objectid.h
 */


/*! \brief InternetGatewayDevice. */
#define MDMOID_IGD  1

/*! \brief InternetGatewayDevice.Firewall. */
#define MDMOID_FIREWALL  2

/*! \brief InternetGatewayDevice.Firewall.X_404A03_IPv4FirewallPriorityCfg.{i}. */
#define MDMOID_FIREWALL_PRIORITY_CFG  3

/*! \brief InternetGatewayDevice.Firewall.X_404A03_IPv4FirewallPriorityRule.{i}. */
#define MDMOID_I_PV4_FIREWALL_PRIORITY_RULE  4

/*! \brief InternetGatewayDevice.X_404A03_IPv6Firewall. */
#define MDMOID_I_PV6_FIREWALL  5

/*! \brief InternetGatewayDevice.X_404A03_ServiceBlkRule.{i}. */
#define MDMOID_SERVICE_BLK_RULE  6

/*! \brief InternetGatewayDevice.UploadDiagnostics. */
#define MDMOID_UPLOAD_DIAGNOSTICS  7

/*! \brief InternetGatewayDevice.UploadDiagnostics.X_404A03_Result.{i}. */
#define MDMOID_UPLOAD_DIAG_RESULT  8

/*! \brief InternetGatewayDevice.Capabilities.PerformanceDiagnostic. */
#define MDMOID_PERFORMANCE_DIAGNOSTIC  9

/*! \brief InternetGatewayDevice.DownloadDiagnostics. */
#define MDMOID_DOWNLOAD_DIAGNOSTICS  10

/*! \brief InternetGatewayDevice.DownloadDiagnostics.X_404A03_Result.{i}. */
#define MDMOID_DOWNLOAD_DIAG_RESULT  11

/*! \brief InternetGatewayDevice.UDPEchoConfig. */
#define MDMOID_UDP_ECHO_CFG  12

/*! \brief InternetGatewayDevice.DeviceInfo. */
#define MDMOID_IGD_DEVICE_INFO  13

/*! \brief InternetGatewayDevice.DeviceInfo.VendorConfigFile.{i}. */
#define MDMOID_VENDOR_CONFIG_FILE  14

/*! \brief InternetGatewayDevice.DeviceInfo.MemoryStatus. */
#define MDMOID_MEMORY_STATUS  15

/*! \brief InternetGatewayDevice.DeviceInfo.ProcessStatus. */
#define MDMOID_PROCESS_STATUS  16

/*! \brief InternetGatewayDevice.DeviceInfo.SessionLog. */
#define MDMOID_SESSION_LOG  17

/*! \brief InternetGatewayDevice.DeviceInfo.X_404A03_LED. */
#define MDMOID_LED  18

/*! \brief InternetGatewayDevice.CaptivePortal. */
#define MDMOID_CAPTIVE_PORTAL  19

/*! \brief InternetGatewayDevice.X_404A03_BpaApiFlowHandle.{i}. */
#define MDMOID_BPA_API_FLOW_HANDLE  20

/*! \brief InternetGatewayDevice.X_404A03_SyslogCfg. */
#define MDMOID_SYSLOG_CFG  21

/*! \brief InternetGatewayDevice.X_404A03_LoginCfg. */
#define MDMOID_LOGIN_CFG  22

/*! \brief InternetGatewayDevice.X_404A03_AppCfg. */
#define MDMOID_APP_CFG  23

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.HttpdCfg. */
#define MDMOID_HTTPD_CFG  24

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.Tr69cCfg. */
#define MDMOID_TR69C_CFG  25

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.Tr64cCfg. */
#define MDMOID_TR64C_CFG  26

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.SshdCfg. */
#define MDMOID_SSHD_CFG  27

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.TelnetdCfg. */
#define MDMOID_TELNETD_CFG  28

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.ConsoledCfg. */
#define MDMOID_CONSOLED_CFG  29

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.SmdCfg. */
#define MDMOID_SMD_CFG  30

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.SskCfg. */
#define MDMOID_SSK_CFG  31

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.SnmpdCfg. */
#define MDMOID_SNMPD_CFG  32

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.FtpdCfg. */
#define MDMOID_FTPD_CFG  33

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.TftpdCfg. */
#define MDMOID_TFTPD_CFG  34

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.PppdCfg. */
#define MDMOID_PPPD_CFG  35

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.IcmpCfg. */
#define MDMOID_ICMP_CFG  36

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.UpnpCfg. */
#define MDMOID_UPNP_CFG  37

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.DnsProxyCfg. */
#define MDMOID_DNS_PROXY_CFG  38

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.DectdCfg. */
#define MDMOID_DECTD_CFG  39

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.VectoringCfg. */
#define MDMOID_VECTORING_CFG  40

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.OmcidCfg. */
#define MDMOID_OMCID_CFG  41

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.LaserdCfg. */
#define MDMOID_LASERD_CFG  42

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.OmciPmdCfg. */
#define MDMOID_OMCI_PMD_CFG  43

/*! \brief InternetGatewayDevice.X_404A03_AppCfg.OsgidCfg. */
#define MDMOID_OSGID_CFG  44

/*! \brief InternetGatewayDevice.X_404A03_PortMappingEntry.{i}. */
#define MDMOID_WAN_CONN_PORTMAPPING  45

/*! \brief InternetGatewayDevice.X_404A03_AccessServiceCfg. */
#define MDMOID_ACCESS_SERVICE_CFG  46

/*! \brief InternetGatewayDevice.X_404A03_AccessServiceCfg.HttpdAccessCntrlCfg. */
#define MDMOID_HTTPD_ACCESS_CNTRL_CFG  47

/*! \brief InternetGatewayDevice.X_404A03_AccessServiceCfg.TelnetdAccessCntrlCfg. */
#define MDMOID_TELNETD_ACCESS_CNTRL_CFG  48

/*! \brief InternetGatewayDevice.X_404A03_AccessServiceCfg.HttpsdAccessCntrlCfg. */
#define MDMOID_HTTPSD_ACCESS_CNTRL_CFG  49

/*! \brief InternetGatewayDevice.X_404A03_EthernetSwitch. */
#define MDMOID_ETHERNET_SWITCH  50

/*! \brief InternetGatewayDevice.X_404A03_AccessListCfg. */
#define MDMOID_ACCESS_HOST_CFG  51

/*! \brief InternetGatewayDevice.X_404A03_AccessHostCfg.{i}. */
#define MDMOID_ACCESS_LIST_CFG  52

/*! \brief InternetGatewayDevice.X_404A03_PortMappingRule.{i}. */
#define MDMOID_PORTMAPPINGRULE  53

/*! \brief InternetGatewayDevice.X_404A03_PwrMngtCfg. */
#define MDMOID_PWR_MNGT  54

/*! \brief InternetGatewayDevice.X_404A03_StandbyCfg. */
#define MDMOID_STANDBY_CFG  55

/*! \brief InternetGatewayDevice.DeviceConfig. */
#define MDMOID_DEVICE_CONFIG  56

/*! \brief InternetGatewayDevice.ManagementServer. */
#define MDMOID_MANAGEMENT_SERVER  57

/*! \brief InternetGatewayDevice.ManagementServer.ManageableDevice.{i}. */
#define MDMOID_MANAGEABLE_DEVICE  58

/*! \brief InternetGatewayDevice.Time. */
#define MDMOID_TIME_SERVER_CFG  59

/*! \brief InternetGatewayDevice.User.{i}. */
#define MDMOID_USER  60

/*! \brief InternetGatewayDevice.X_404A03_UserDefaultConfig. */
#define MDMOID_USER_DEFAULT_CONFIG  61

/*! \brief InternetGatewayDevice.UserInterface. */
#define MDMOID_USER_INTERFACE_CFG  62

/*! \brief InternetGatewayDevice.UserInterface.RemoteAccess. */
#define MDMOID_REMOTE_ACCESS_CFG  63

/*! \brief InternetGatewayDevice.UserInterface.RemoteAccess.X_404A03_Telnet. */
#define MDMOID_TELNET  64

/*! \brief InternetGatewayDevice.UserInterface.RemoteAccess.X_404A03_SSH. */
#define MDMOID_SSH  65

/*! \brief InternetGatewayDevice.UserInterface.RemoteAccess.X_404A03_SupportConsole. */
#define MDMOID_SUPPORT_CONSOLE  66

/*! \brief InternetGatewayDevice.Layer2Bridging. */
#define MDMOID_L2_BRIDGING  67

/*! \brief InternetGatewayDevice.Layer2Bridging.Bridge.{i}. */
#define MDMOID_L2_BRIDGING_ENTRY  68

/*! \brief InternetGatewayDevice.Layer2Bridging.Filter.{i}. */
#define MDMOID_L2_BRIDGING_FILTER  69

/*! \brief InternetGatewayDevice.Layer2Bridging.AvailableInterface.{i}. */
#define MDMOID_L2_BRIDGING_INTF  70

/*! \brief InternetGatewayDevice.QueueManagement. */
#define MDMOID_Q_MGMT  71

/*! \brief InternetGatewayDevice.QueueManagement.Classification.{i}. */
#define MDMOID_Q_MGMT_CLASSIFICATION  72

/*! \brief InternetGatewayDevice.QueueManagement.Policer.{i}. */
#define MDMOID_Q_MGMT_POLICER  73

/*! \brief InternetGatewayDevice.QueueManagement.Queue.{i}. */
#define MDMOID_Q_MGMT_QUEUE  74

/*! \brief InternetGatewayDevice.LANConfigSecurity. */
#define MDMOID_LANCONFIG_SECURITY  75

/*! \brief InternetGatewayDevice.IPPingDiagnostics. */
#define MDMOID_IP_PING_DIAG  76

/*! \brief InternetGatewayDevice.TraceRouteDiagnostics. */
#define MDMOID_TRACE_ROUTE_DIAG  77

/*! \brief InternetGatewayDevice.TraceRouteDiagnostics.RouteHops.{i}. */
#define MDMOID_TRACE_ROUTE_HOPS  78

/*! \brief InternetGatewayDevice.EponSoftwareImage.{i}. */
#define MDMOID_EPON_SOFTWARE_IMAGE  79

/*! \brief InternetGatewayDevice.LANDevice.{i}. */
#define MDMOID_LAN_DEV  80

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_IgmpSnoopingConfig. */
#define MDMOID_IGMP_SNOOPING_CFG  81

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement. */
#define MDMOID_LAN_HOST_CFG  82

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPStaticAddress.{i}. */
#define MDMOID_DHCP_STATIC_ADDR  83

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}. */
#define MDMOID_LAN_IP_INTF  84

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_404A03_IPv6LanIntfAddress. */
#define MDMOID_I_PV6_LAN_INTF_ADDR  85

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_404A03_IPv6LanIntfAddress.DelegatedAddress.{i}. */
#define MDMOID_DELEGATED_ADDRESS  86

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_404A03_FirewallException.{i}. */
#define MDMOID_LAN_IP_INTF_FIREWALL_EXCEPTION  87

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_404A03_IpFilterCfg.{i}. */
#define MDMOID_IP_FILTER_CFG  88

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_404A03_ServiceBlkCfg.{i}. */
#define MDMOID_SERVICE_BLK_CFG  89

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}. */
#define MDMOID_DHCP_CONDITIONAL_SERVING  90

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}.DHCPOption.{i}. */
#define MDMOID_DHCP_COND_SERV_OPTION  91

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_IPv6LANHostConfigManagement. */
#define MDMOID_I_PV6_LAN_HOST_CFG  92

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_IPv6LANHostConfigManagement.RadvdConfigManagement. */
#define MDMOID_RADVD_CONFIG_MGT  93

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_IPv6LANHostConfigManagement.RadvdConfigManagement.ULAPrefixInfo. */
#define MDMOID_ULA_PREFIX_INFO  94

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_IPv6LANHostConfigManagement.RadvdConfigManagement.PrefixInformation.{i}. */
#define MDMOID_PREFIX_INFO  95

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_IPv6LANHostConfigManagement.X_404A03_MldSnoopingConfig. */
#define MDMOID_MLD_SNOOPING_CFG  96

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}. */
#define MDMOID_LAN_ETH_INTF  97

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_ETH_INTF_STATS  98

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}. */
#define MDMOID_LAN_USB_INTF  99

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_USB_INTF_STATS  100

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}. */
#define MDMOID_LAN_WLAN  101

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.AssociatedDevice.{i}. */
#define MDMOID_LAN_WLAN_ASSOCIATED_DEVICE_ENTRY  102

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WEPKey.{i}. */
#define MDMOID_LAN_WLAN_WEP_KEY  103

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.PreSharedKey.{i}. */
#define MDMOID_LAN_WLAN_PRE_SHARED_KEY  104

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.Stats. */
#define MDMOID_LAN_WLAN_STATS  105

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WPS. */
#define MDMOID_LAN_WLAN_WPS  106

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WPS.Registrar.{i}. */
#define MDMOID_LAN_WLAN_WPS_REGISTRAR  107

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.APWMMParameter.{i}. */
#define MDMOID_APWMM_PARAMETER  108

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.STAWMMParameter.{i}. */
#define MDMOID_STAWMM_PARAMETER  109

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter. */
#define MDMOID_WLAN_ADAPTER  110

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.WlBaseCfg. */
#define MDMOID_WL_BASE_CFG  111

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.WlStaticWdsCfg.{i}. */
#define MDMOID_WL_STATIC_WDS_CFG  112

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.WlWdsCfg.{i}. */
#define MDMOID_WL_WDS_CFG  113

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.WlScanWdsCfg.{i}. */
#define MDMOID_WL_SCAN_WDS_CFG  114

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.WlMimoCfg. */
#define MDMOID_WL_MIMO_CFG  115

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.WlWmmCfg. */
#define MDMOID_WL_WMM_CFG  116

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.WlWMMCfg.WlAPWmmParameterCfg.{i}. */
#define MDMOID_AP_WMM_PARAMETER_CFG  117

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.WlWMMCfg.WlSTAWmmParameterCfg.{i}. */
#define MDMOID_STA_WMM_PARAMETER_CFG  118

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.WlSesCfg. */
#define MDMOID_WL_SES_CFG  119

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.WlVirtIntfCfg.{i}. */
#define MDMOID_WL_VIRT_INTF_CFG  120

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.VirtIntf.{i}.WlMacFltCfg.{i}. */
#define MDMOID_WL_MAC_FLT  121

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.VirtIntf.{i}.WlKey64Cfg.{i}. */
#define MDMOID_WL_KEY64_CFG  122

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.VirtIntf.{i}.WlKey128Cfg.{i}. */
#define MDMOID_WL_KEY128_CFG  123

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WlanAdapter.VirtIntf.{i}.WlWpsCfg. */
#define MDMOID_WL_WPS_CFG  124

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_404A03_WLANVirtMbssConfiguration.{i}. */
#define MDMOID_LAN_WLAN_VIRT_MBSS  125

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_LANMocaInterfaceConfig.{i}. */
#define MDMOID_LAN_MOCA_INTF  126

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_LANMocaInterfaceConfig.{i}.Status. */
#define MDMOID_LAN_MOCA_INTF_STATUS  127

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_LANMocaInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_MOCA_INTF_STATS  128

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_LANEponInterfaceConfig.{i}. */
#define MDMOID_LAN_EPON_INTF  129

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_LANEponInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_EPON_INTF_STATS  130

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_IGMP. */
#define MDMOID_IGMP  131

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_IGMP.CacheTable.{i}. */
#define MDMOID_CACHE_TABLE  132

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_404A03_ALG.{i}. */
#define MDMOID_ALG  133

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts. */
#define MDMOID_LAN_HOSTS  134

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts.Host.{i}. */
#define MDMOID_LAN_HOST_ENTRY  135

/*! \brief InternetGatewayDevice.WANDevice.{i}. */
#define MDMOID_WAN_DEV  136

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig. */
#define MDMOID_WAN_COMMON_INTF_CFG  137

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_404A03_XTM_Interface_Stats.{i}. */
#define MDMOID_XTM_INTERFACE_STATS  138

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig. */
#define MDMOID_WAN_DSL_INTF_CFG  139

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.X_404A03_BertTest. */
#define MDMOID_WAN_BERT_TEST  140

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats. */
#define MDMOID_WAN_DSL_INTF_STATS  141

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Total. */
#define MDMOID_WAN_DSL_INTF_STATS_TOTAL  142

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Showtime. */
#define MDMOID_WAN_DSL_INTF_STATS_SHOWTIME  143

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.CurrentDay. */
#define MDMOID_WAN_DSL_INTF_STATS_CURRENT_DAY  144

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.QuarterHour. */
#define MDMOID_WAN_DSL_INTF_STATS_QUARTER_HOUR  145

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.TestParams. */
#define MDMOID_WAN_DSL_TEST_PARAMS  146

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig. */
#define MDMOID_WAN_ETH_INTF  147

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.X_404A03_IPv6Address.{i}. */
#define MDMOID_I_PV6_ADDR  148

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.Stats. */
#define MDMOID_WAN_ETH_INTF_STATS  149

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_404A03_WANMocaInterfaceConfig. */
#define MDMOID_WAN_MOCA_INTF  150

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_404A03_WANMocaInterfaceConfig.Status. */
#define MDMOID_WAN_MOCA_INTF_STATUS  151

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_404A03_WANMocaInterfaceConfig.Stats. */
#define MDMOID_WAN_MOCA_INTF_STATS  152

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_404A03_EponInterfaceConfig. */
#define MDMOID_WAN_EPON_INTF  153

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_404A03_EponInterfaceConfig.Stats. */
#define MDMOID_WAN_EPON_INTF_STATS  154

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_404A03_L2tpAcIntfConfig. */
#define MDMOID_L2TP_AC_INTF_CONFIG  155

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_404A03_WANPonInterfaceConfig. */
#define MDMOID_WAN_PON_INTF  156

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_404A03_WANPonInterfaceConfig.Stats. */
#define MDMOID_WAN_PON_INTF_STATUS  157

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLDiagnostics. */
#define MDMOID_WAN_DSL_DIAG  158

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_404A03_WANDSLDiagnostics. */
#define MDMOID_WAN_DSL_PROPRIETARY_DIAG  159

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_404A03_WANDSLDiagnostics.PeakLineNoise. */
#define MDMOID_WAN_DSL_DIAG_PLN  160

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_404A03_WANDSLDiagnostics.NonLinearity. */
#define MDMOID_WAN_DSL_DIAG_NON_LINEARITY  161

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}. */
#define MDMOID_WAN_CONN_DEVICE  162

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_404A03_WANATMF4EndToEndLoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F4_END_TO_END_LOOPBACK_DIAG  163

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_404A03_WANATMF4LoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F4_LOOPBACK_DIAG  164

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_404A03_WANATMF5EndToEndLoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F5_END_TO_END_LOOPBACK_DIAG  165

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_404A03_WANGPONLinkConfig. */
#define MDMOID_WAN_GPON_LINK_CFG  166

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_404A03_WANEPONLinkConfig. */
#define MDMOID_WAN_EPON_LINK_CFG  167

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig. */
#define MDMOID_WAN_DSL_LINK_CFG  168

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig.X_404A03_ATM_PARMS. */
#define MDMOID_WAN_DSL_ATM_PARAMS  169

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANATMF5LoopbackDiagnostics. */
#define MDMOID_WAN_ATM5_LOOPBACK_DIAG  170

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPTMLinkConfig. */
#define MDMOID_WAN_PTM_LINK_CFG  171

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANEthernetLinkConfig. */
#define MDMOID_WAN_ETH_LINK_CFG  172

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_404A03_L2tpAcLinkConfig. */
#define MDMOID_L2TP_AC_LINK_CONFIG  173

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}. */
#define MDMOID_WAN_IP_CONN  174

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.PortMapping.{i}. */
#define MDMOID_WAN_IP_CONN_PORTMAPPING  175

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_404A03_UPNPPortMappingRule.{i}. */
#define MDMOID_UPNP_IP_PORTMAPPING  176

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_404A03_PortTriggering.{i}. */
#define MDMOID_WAN_IP_CONN_PORT_TRIGGERING  177

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_404A03_FirewallException.{i}. */
#define MDMOID_WAN_IP_CONN_FIREWALL_EXCEPTION  178

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_404A03_MacFilterObj. */
#define MDMOID_MAC_FILTER  179

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_404A03_MacFilterObj.X_404A03_MacFilterCfg.{i}. */
#define MDMOID_MAC_FILTER_CFG  180

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.Stats. */
#define MDMOID_WAN_IP_CONN_STATS  181

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}. */
#define MDMOID_WAN_PPP_CONN  182

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.PortMapping.{i}. */
#define MDMOID_WAN_PPP_CONN_PORTMAPPING  183

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_404A03_UPNPPortMappingRule.{i}. */
#define MDMOID_UPNP_PPP_PORTMAPPING  184

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_404A03_PortTriggering.{i}. */
#define MDMOID_WAN_PPP_CONN_PORT_TRIGGERING  185

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_404A03_FirewallException.{i}. */
#define MDMOID_WAN_PPP_CONN_FIREWALL_EXCEPTION  186

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.Stats. */
#define MDMOID_WAN_PPP_CONN_STATS  187

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_404A03_WANIPv6Connection.{i}. */
#define MDMOID_WAN_IPV6_CONN  188

/*! \brief InternetGatewayDevice.X_404A03_VlanAutoHunt. */
#define MDMOID_VLAN_AUTO_HUNT  189

/*! \brief InternetGatewayDevice.X_404A03_VlanAutoHunt.VlanHuntInfo.{i}. */
#define MDMOID_VLAN_HUNT_INFO  190

/*! \brief InternetGatewayDevice.X_404A03_VlanAutoHunt.HuntWAN.{i}.VlanHuntRule.{i}. */
#define MDMOID_VLAN_HUNT_RULE  191

/*! \brief InternetGatewayDevice.Layer3Forwarding. */
#define MDMOID_L3_FORWARDING  192

/*! \brief InternetGatewayDevice.Layer3Forwarding.Forwarding.{i}. */
#define MDMOID_L3_FORWARDING_ENTRY  193

/*! \brief InternetGatewayDevice.X_404A03_IPv6Layer3Forwarding. */
#define MDMOID_I_PV6_L3_FORWARDING  194

/*! \brief InternetGatewayDevice.X_404A03_IPv6Layer3Forwarding.IPv6Forwarding.{i}. */
#define MDMOID_I_PV6_L3_FORWARDING_ENTRY  195

/*! \brief InternetGatewayDevice.Services. */
#define MDMOID_SERVICES  196

/*! \brief InternetGatewayDevice.Services.StorageService.{i}. */
#define MDMOID_STORAGE_SERVICE  197

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.UserAccount.{i}. */
#define MDMOID_USER_ACCOUNT  198

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.Capabilites. */
#define MDMOID_CAPABILITES  199

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.NetInfo. */
#define MDMOID_NETWORK_INFO  200

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.NetworkServer. */
#define MDMOID_NETWORK_SERVER  201

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.PhysicalMedium.{i}. */
#define MDMOID_PHYSICAL_MEDIUM  202

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.LogicalVolume.{i}. */
#define MDMOID_LOGICAL_VOLUME  203

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.LogicalVolume.{i}.Folder.{i}. */
#define MDMOID_FOLDER  204

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}. */
#define MDMOID_VOICE  205

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Call.{i}. */
#define MDMOID_VOICE_CALL_LIST  206

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Call.{i}.NewFlag. */
#define MDMOID_VOICE_CALL_NEW_FLAG  207

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Call.{i}.NumberOfMissedCalls. */
#define MDMOID_VOICE_CALL_NUMBER_OF_MISSED_CALLS  208

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Call.{i}.Number. */
#define MDMOID_VOICE_CALL_NUMBER  209

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Call.{i}.Name. */
#define MDMOID_VOICE_CALL_NAME  210

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Call.{i}.DateTime. */
#define MDMOID_VOICE_CALL_DATE_TIME  211

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Call.{i}.LineName. */
#define MDMOID_VOICE_CALL_LINE_NAME  212

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Call.{i}.LineId. */
#define MDMOID_VOICE_CALL_LINE_ID  213

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Call.{i}.CallType. */
#define MDMOID_VOICE_CALL_TYPE  214

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_InternalName.{i}. */
#define MDMOID_VOICE_INTERNAL_NAME_LIST  215

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_InternalName.{i}.TerminalNumber. */
#define MDMOID_VOICE_TERMINAL_NUMBER  216

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_InternalName.{i}.Name. */
#define MDMOID_VOICE_INTERNAL_NAME  217

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Contact.{i}. */
#define MDMOID_VOICE_CONTACT_LIST  218

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Contact.{i}.Name. */
#define MDMOID_VOICE_CONTACT_NAME  219

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Contact.{i}.FirstName. */
#define MDMOID_VOICE_CONTACT_FIRST_NAME  220

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Contact.{i}.ContactNumber. */
#define MDMOID_VOICE_CONTACT_NUMBER  221

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Contact.{i}.Melody. */
#define MDMOID_VOICE_CONTACT_MELODY  222

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Contact.{i}.LineId. */
#define MDMOID_VOICE_CONTACT_LINE_ID  223

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_SupportList.{i}. */
#define MDMOID_VOICE_DECT_SUPPORT_LIST  224

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities. */
#define MDMOID_VOICE_CAP  225

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.SIP. */
#define MDMOID_VOICE_CAP_SIP  226

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.MGCP. */
#define MDMOID_VOICE_CAP_MGCP  227

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.Codecs.{i}. */
#define MDMOID_VOICE_CAP_CODECS  228

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}. */
#define MDMOID_VOICE_PROF  229

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.ServiceProviderInfo. */
#define MDMOID_VOICE_PROF_PROVIDER  230

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.SIP. */
#define MDMOID_VOICE_PROF_SIP  231

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.SIP.EventSubscribe.{i}. */
#define MDMOID_VOICE_PROF_SIP_SUBSCRIBE  232

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.MGCP. */
#define MDMOID_VOICE_PROF_MGCP  233

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.RTP. */
#define MDMOID_VOICE_PROF_RTP  234

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.RTP.SRTP. */
#define MDMOID_VOICE_PROF_RTP_SRTP  235

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.FaxT38. */
#define MDMOID_VOICE_PROF_FAX_T38  236

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}. */
#define MDMOID_VOICE_LINE  237

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.SIP. */
#define MDMOID_VOICE_LINE_SIP  238

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.CallingFeatures. */
#define MDMOID_VOICE_LINE_CALLING_FEATURES  239

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.VoiceProcessing. */
#define MDMOID_VOICE_LINE_PROCESSING  240

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec. */
#define MDMOID_VOICE_LINE_CODEC  241

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec.List.{i}. */
#define MDMOID_VOICE_LINE_CODEC_LIST  242

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Stats. */
#define MDMOID_VOICE_LINE_STATS  243

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_404A03_LineSetting. */
#define MDMOID_VOICE_LINE_SETTING  244

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_404A03_DectLineSetting.LineName. */
#define MDMOID_VOICE_LINE_NAME  245

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_404A03_DectLineSetting.LineId. */
#define MDMOID_VOICE_LINE_DECT_LINE_ID  246

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_404A03_DectLineSetting.AttachedHandset. */
#define MDMOID_VOICE_LINE_ATTACHED_HANDSET  247

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_404A03_DectLineSetting.Melody. */
#define MDMOID_VOICE_LINE_MELODY  248

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_404A03_DectLineSetting.DialingPrefix. */
#define MDMOID_VOICE_LINE_DIALING_PREFIX  249

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_404A03_DectLineSetting.Volumn. */
#define MDMOID_VOICE_LINE_VOLUMN  250

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_404A03_DectLineSetting.BlockedNumber. */
#define MDMOID_VOICE_LINE_BLOCKED_NUMBER  251

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_404A03_DectLineSetting.MultiCallMode. */
#define MDMOID_VOICE_LINE_MULTI_CALL_MODE  252

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_404A03_DectLineSetting.IntrusionCall. */
#define MDMOID_VOICE_LINE_INTRUSION_CALL  253

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_404A03_DectLineSetting.CLIR. */
#define MDMOID_CLI_R  254

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_404A03_DectLineSetting.CallForwarding. */
#define MDMOID_VOICE_LINE_CALL_FORWARDING  255

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.PhyInterface.{i}. */
#define MDMOID_VOICE_PHY_INTF  256

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.PhyInterface.{i}.Tests. */
#define MDMOID_VOICE_PHY_INTF_TESTS  257

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_PSTN.{i}. */
#define MDMOID_VOICE_PSTN  258

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Ntr. */
#define MDMOID_VOICE_NTR  259

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_404A03_Ntr.History.{i}. */
#define MDMOID_VOICE_NTR_HISTORY  260

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface. */
#define MDMOID_VOICE_DECT_SYSTEM_SETTING  261

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.Handset.{i}. */
#define MDMOID_DECT_HANDSET  262

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.PINCode. */
#define MDMOID_VOICE_DECT_PIN_CODE  263

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.ClockMaster. */
#define MDMOID_VOICE_DECT_CLOCK_MASTER  264

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.ResetBase. */
#define MDMOID_VOICE_DECT_RESET_BASE  265

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.FirmwareVersion. */
#define MDMOID_VOICE_DECT_FIRMWARE_VERSION  266

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.HardwareVersion. */
#define MDMOID_VOICE_DECT_HARDWARE_VERSION  267

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.EEPROMVersion. */
#define MDMOID_EEPROM_VERSION  268

/*! \brief InternetGatewayDevice.X_404A03_SnmpCfg. */
#define MDMOID_SNMP_CFG  269

/*! \brief InternetGatewayDevice.X_404A03_SecDmzHostCfg. */
#define MDMOID_SEC_DMZ_HOST_CFG  270

/*! \brief InternetGatewayDevice.X_404A03_AccessTimeRestriction.{i}. */
#define MDMOID_ACCESS_TIME_RESTRICTION  271

/*! \brief InternetGatewayDevice.X_404A03_UrlFilterCfg. */
#define MDMOID_URL_FILTER_CFG  272

/*! \brief InternetGatewayDevice.X_404A03_UrlFilterCfg.X_404A03_UrlFilterListCfgObj.{i}. */
#define MDMOID_URL_FILTER_LIST  273

/*! \brief InternetGatewayDevice.X_404A03_DDnsCfg.{i}. */
#define MDMOID_D_DNS_CFG  274

/*! \brief InternetGatewayDevice.X_404A03_IPPCfg. */
#define MDMOID_IPP_CFG  275

/*! \brief InternetGatewayDevice.X_404A03_DLNA. */
#define MDMOID_DLNA  276

/*! \brief InternetGatewayDevice.X_404A03_DLNA.DmsCfg. */
#define MDMOID_DMS_CFG  277

/*! \brief InternetGatewayDevice.X_404A03_DebugPortMirroringCfg.{i}. */
#define MDMOID_WAN_DEBUG_PORT_MIRRORING_CFG  278

/*! \brief InternetGatewayDevice.X_404A03_IPSecCfg.{i}. */
#define MDMOID_IP_SEC_CFG  279

/*! \brief InternetGatewayDevice.X_404A03_CertificateCfg.{i}. */
#define MDMOID_CERTIFICATE_CFG  280

/*! \brief InternetGatewayDevice.X_404A03_WapiCertificate. */
#define MDMOID_WAPI_CERTIFICATE  281

/*! \brief InternetGatewayDevice.X_404A03_WapiCertificate.WapiAsCertificate. */
#define MDMOID_WAPI_AS_CERTIFICATE  282

/*! \brief InternetGatewayDevice.X_404A03_WapiCertificate.WapiIssuedCertificate. */
#define MDMOID_WAPI_ISSUED_CERTIFICATE  283

/*! \brief InternetGatewayDevice.X_404A03_NetworkConfig. */
#define MDMOID_NETWORK_CONFIG  284

/*! \brief InternetGatewayDevice.X_404A03_InterfaceControl. */
#define MDMOID_INTERFACE_CONTROL  285

/*! \brief InternetGatewayDevice.X_404A03_P8021agCfg. */
#define MDMOID_P8021AG_CFG  286

/*! \brief InternetGatewayDevice.X_404A03_IGMPCfg. */
#define MDMOID_IGMP_CFG  287

/*! \brief InternetGatewayDevice.X_404A03_MLDCfg. */
#define MDMOID_MLD_CFG  288

/*! \brief InternetGatewayDevice.X_404A03_NUD. */
#define MDMOID_NUD  289

/*! \brief InternetGatewayDevice.X_404A03_IPTunnel.{i}. */
#define MDMOID_IP_TUNNEL  290

/*! \brief InternetGatewayDevice.X_404A03_IPTunnel.{i}.V4inV6Tunnel.{i}. */
#define MDMOID_IPV4IN_IPV6_TUNNEL  291

/*! \brief InternetGatewayDevice.X_404A03_IPTunnel.{i}.V6inV4Tunnel.{i}. */
#define MDMOID_IPV6IN_IPV4_TUNNEL  292

/*! \brief InternetGatewayDevice.X_ITU_T_ORG. */
#define MDMOID_ITU_T_ORG  293

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4. */
#define MDMOID_G_984_4  294

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement. */
#define MDMOID_EQUIPMENT_MANAGEMENT  295

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.OntG. */
#define MDMOID_ONT_G  296

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.Ont2G. */
#define MDMOID_ONT2_G  297

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.OntData. */
#define MDMOID_ONT_DATA  298

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.SoftwareImage.{i}. */
#define MDMOID_SOFTWARE_IMAGE  299

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.CardHolder.{i}. */
#define MDMOID_CARD_HOLDER  300

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.CircuitPack.{i}. */
#define MDMOID_CIRCUIT_PACK  301

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.PowerShedding.{i}. */
#define MDMOID_POWER_SHEDDING  302

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.PortMappingPackageG.{i}. */
#define MDMOID_PORT_MAPPING_PACKAGE_G  303

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement. */
#define MDMOID_ANI_MANAGEMENT  304

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.AniG.{i}. */
#define MDMOID_ANI_G  305

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.TCont.{i}. */
#define MDMOID_T_CONT  306

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemPortNetworkCtp.{i}. */
#define MDMOID_GEM_PORT_NETWORK_CTP  307

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemInterworkingTp.{i}. */
#define MDMOID_GEM_INTERWORKING_TP  308

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.MulticastGemInterworkingTp.{i}. */
#define MDMOID_MULTICAST_GEM_INTERWORKING_TP  309

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.MulticastGemInterworkingTp.{i}.MulticastAddressTable.{i}. */
#define MDMOID_GEM_INTERWORKING_TP_MULTICAST_ADDRESS_TABLE  310

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemPortPmHistoryData.{i}. */
#define MDMOID_GEM_PORT_PM_HISTORY_DATA  311

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GalEthernetProfile.{i}. */
#define MDMOID_GAL_ETHERNET_PROFILE  312

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GalEthernetPmHistoryData.{i}. */
#define MDMOID_GAL_ETHERNET_PM_HISTORY_DATA  313

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.FecPmHistoryData.{i}. */
#define MDMOID_FEC_PM_HISTORY_DATA  314

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices. */
#define MDMOID_LAYER2_DATA_SERVICES  315

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgeServiceProfile.{i}. */
#define MDMOID_MAC_BRIDGE_SERVICE_PROFILE  316

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_404A03_MacBridgeServiceProfile.{i}. */
#define MDMOID_BC_MAC_BRIDGE_SERVICE_PROFILE  317

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgeConfigData.{i}. */
#define MDMOID_MAC_BRIDGE_CONFIG_DATA  318

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePmHistoryData.{i}. */
#define MDMOID_MAC_BRIDGE_PM_HISTORY_DATA  319

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortConfigData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_CONFIG_DATA  320

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortDesignationData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_DESIGNATION_DATA  321

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterTableData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_FILTER_TABLE_DATA  322

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterTableData.{i}.MacFilterTable.{i}. */
#define MDMOID_MAC_FILTER_TABLE  323

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterPreAssignTable.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_FILTER_PRE_ASSIGN_TABLE  324

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortBridgeTableData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_BRIDGE_TABLE_DATA  325

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortBridgeTableData.{i}.BridgeTable.{i}. */
#define MDMOID_BRIDGE_TABLE  326

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortPmHistoryData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_PM_HISTORY_DATA  327

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MapperServiceProfile.{i}. */
#define MDMOID_MAPPER_SERVICE_PROFILE  328

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_404A03_MapperServiceProfile.{i}. */
#define MDMOID_BC_MAPPER_SERVICE_PROFILE  329

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.VlanTaggingFilterData.{i}. */
#define MDMOID_VLAN_TAGGING_FILTER_DATA  330

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.VlanTaggingOperationConfigurationData.{i}. */
#define MDMOID_VLAN_TAGGING_OPERATION_CONFIGURATION_DATA  331

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.ExtendedVlanTaggingOperationConfigurationData.{i}. */
#define MDMOID_EXTENDED_VLAN_TAGGING_OPERATION_CONFIGURATION_DATA  332

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.ExtendedVlanTaggingOperationConfigurationData.{i}.ReceivedFrameVlanTaggingOperationTable.{i}. */
#define MDMOID_RECEIVED_FRAME_VLAN_TAGGING_OPERATION_TABLE  333

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}. */
#define MDMOID_MULTICAST_OPERATIONS_PROFILE  334

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.DynamicAccessControlListTable.{i}. */
#define MDMOID_DYNAMIC_ACCESS_CONTROL_LIST_TABLE  335

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.StaticAccessControlListTable.{i}. */
#define MDMOID_STATIC_ACCESS_CONTROL_LIST_TABLE  336

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.LostGroupsListTable.{i}. */
#define MDMOID_LOST_GROUPS_LIST_TABLE  337

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberConfigInfo.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER_CONFIG_INFO  338

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberMonitor.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER_MONITOR  339

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberMonitor.{i}.ActiveGroupsListTable.{i}. */
#define MDMOID_ACTIVE_GROUPS_LIST_TABLE  340

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_404A03_MulticastSubscriberMonitor.{i}. */
#define MDMOID_BC_MULTICAST_SUBSCRIBER_MONITOR  341

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_404A03_MulticastSubscriberMonitor.{i}.MulticastSubscriber.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER  342

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.UpstreamEthernetFramePmHistoryData.{i}. */
#define MDMOID_UPSTREAM_ETHERNET_FRAME_PM_HISTORY_DATA  343

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.DownstreamEthernetFramePmHistoryData.{i}. */
#define MDMOID_DOWNSTREAM_ETHERNET_FRAME_PM_HISTORY_DATA  344

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices. */
#define MDMOID_LAYER3_DATA_SERVICES  345

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.IpHostConfigData.{i}. */
#define MDMOID_IP_HOST_CONFIG_DATA  346

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.X_404A03_IpHostConfigData.{i}. */
#define MDMOID_BC_IP_HOST_CONFIG_DATA  347

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.IpHostPmHistoryData.{i}. */
#define MDMOID_IP_HOST_PM_HISTORY_DATA  348

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}. */
#define MDMOID_IPV6_HOST_CONFIG_DATA  349

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentAddressTable.{i}. */
#define MDMOID_IPV6_CURRENT_ADDRESS_TABLE  350

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentDefaultRouterTable.{i}. */
#define MDMOID_IPV6_CURRENT_DEFAULT_ROUTER_TABLE  351

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentDnsTable.{i}. */
#define MDMOID_IPV6_CURRENT_DNS_TABLE  352

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentOnlinkPrefixTable.{i}. */
#define MDMOID_IPV6_CURRENT_ONLINK_PREFIX_TABLE  353

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.X_404A03_Ipv6HostConfigData.{i}. */
#define MDMOID_BC_IPV6_HOST_CONFIG_DATA  354

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.TcpUdpConfigData.{i}. */
#define MDMOID_TCP_UDP_CONFIG_DATA  355

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices. */
#define MDMOID_ETHERNET_SERVICES  356

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.PptpEthernetUni.{i}. */
#define MDMOID_PPTP_ETHERNET_UNI  357

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA  358

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData2.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA2  359

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData3.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA3  360

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.VirtualEthernetInterfacePoint.{i}. */
#define MDMOID_VIRTUAL_ETHERNET_INTERFACE_POINT  361

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices. */
#define MDMOID_VOICE_SERVICES  362

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.PptpPotsUni.{i}. */
#define MDMOID_PPTP_POTS_UNI  363

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipUserData.{i}. */
#define MDMOID_SIP_USER_DATA  364

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipAgentConfigData.{i}. */
#define MDMOID_SIP_AGENT_CONFIG_DATA  365

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpVoiceCtp.{i}. */
#define MDMOID_VO_IP_VOICE_CTP  366

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpMediaProfile.{i}. */
#define MDMOID_VO_IP_MEDIA_PROFILE  367

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoiceServiceProfile.{i}. */
#define MDMOID_VOICE_SERVICE  368

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.RtpProfileData.{i}. */
#define MDMOID_RTP_PROFILE_DATA  369

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpAppServiceProfile.{i}. */
#define MDMOID_VO_IP_APP_SERVICE_PROFILE  370

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoiceFeatureAccessCodes.{i}. */
#define MDMOID_VOICE_FEATURE_ACCESS_CODES  371

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.NetworkDialPlanTable.{i}. */
#define MDMOID_NETWORK_DIAL_PLAN_TABLE  372

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.NetworkDialPlanTable.{i}.DialPlanTable.{i}. */
#define MDMOID_DIAL_PLAN_TABLE  373

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpLineStatus.{i}. */
#define MDMOID_VO_IP_LINE_STATUS  374

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.CallControlPmHistoryData.{i}. */
#define MDMOID_CALL_CONTROL_PM_HISTORY_DATA  375

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.RtpPmHistoryData.{i}. */
#define MDMOID_RTP_PM_HISTORY_DATA  376

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipAgentPmHistoryData.{i}. */
#define MDMOID_SIP_AGENT_PM_HISTORY_DATA  377

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipCallInitPmHistoryData.{i}. */
#define MDMOID_SIP_CALL_INIT_PM_HISTORY_DATA  378

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.MgcConfigData.{i}. */
#define MDMOID_MGC_CONFIG_DATA  379

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.MgcPmHistoryData.{i}. */
#define MDMOID_MGC_PM_HISTORY_DATA  380

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpConfigData.{i}. */
#define MDMOID_VO_IP_CONFIG_DATA  381

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices. */
#define MDMOID_MOCA_SERVICES  382

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.PptpMocaUni.{i}. */
#define MDMOID_PPTP_MOCA_UNI  383

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_404A03_PptpMocaUni.{i}. */
#define MDMOID_BRCM_PPTP_MOCA_UNI  384

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_404A03_MocaStatus.{i}. */
#define MDMOID_MOCA_STATUS  385

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_404A03_MocaStats.{i}. */
#define MDMOID_MOCA_STATS  386

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaEthernetPmHistoryData.{i}. */
#define MDMOID_MOCA_ETHERNET_PM_HISTORY_DATA  387

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaInterfacePmHistoryData.{i}. */
#define MDMOID_MOCA_INTERFACE_PM_HISTORY_DATA  388

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaInterfacePmHistoryData.{i}.NodeTable.{i}. */
#define MDMOID_MOCA_INTERFACE_PM_HISTORY_DATA_NODE_TABLE  389

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement. */
#define MDMOID_TRAFFIC_MANAGEMENT  390

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.PriorityQueueG.{i}. */
#define MDMOID_PRIORITY_QUEUE_G  391

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.TrafficSchedulerG.{i}. */
#define MDMOID_TRAFFIC_SCHEDULER_G  392

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.GemTrafficDescriptor.{i}. */
#define MDMOID_GEM_TRAFFIC_DESCRIPTOR  393

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General. */
#define MDMOID_GENERAL  394

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.UniG.{i}. */
#define MDMOID_UNI_G  395

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.OltG. */
#define MDMOID_OLT_G  396

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.NetworkAddress.{i}. */
#define MDMOID_NETWORK_ADDRESS  397

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.AuthenticationSecurityMethod.{i}. */
#define MDMOID_AUTHENTICATION_SECURITY_METHOD  398

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.LargeString.{i}. */
#define MDMOID_LARGE_STRING  399

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.ThresholdData1.{i}. */
#define MDMOID_THRESHOLD_DATA1  400

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.ThresholdData2.{i}. */
#define MDMOID_THRESHOLD_DATA2  401

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.Omci. */
#define MDMOID_OMCI  402

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.TR069ManagementServer.{i}. */
#define MDMOID_TR069_MANAGEMENT_SERVER  403

/*! \brief InternetGatewayDevice.X_404A03_OmciSystem. */
#define MDMOID_OMCI_SYSTEM  404

/*! \brief InternetGatewayDevice.X_404A03_GponOmciStats. */
#define MDMOID_GPON_OMCI_STATS  405

/*! \brief InternetGatewayDevice.X_404A03_WlanNvram. */
#define MDMOID_WLAN_NVRAM  406

/*! \brief InternetGatewayDevice.X_404A03_DefaultPPPConfig. */
#define MDMOID_PPP_DEFAULT_CONFIG  407

/*! \brief InternetGatewayDevice.X_CT_OAM. */
#define MDMOID_CTOAM  408

/*! \brief InternetGatewayDevice.X_CT_OAM.IADInfo. */
#define MDMOID_OAMIAD_INFO  409

/*! \brief InternetGatewayDevice.X_CT_OAM.GlobalParameterConfig. */
#define MDMOID_OAM_GLB_PARAM_CFG  410

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPParameterConfig. */
#define MDMOID_OAMSIP_PARAM_CFG  411

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPUserParameterConfig. */
#define MDMOID_OAMSIP_USR_PARAM_CFG  412

/*! \brief InternetGatewayDevice.X_CT_OAM.FAXModemConfig. */
#define MDMOID_OAMFAXMD_CFG  413

/*! \brief InternetGatewayDevice.X_CT_OAM.POTSStatus. */
#define MDMOID_OAMPOTS_STS  414

/*! \brief InternetGatewayDevice.X_CT_OAM.IADOperation. */
#define MDMOID_OAMIAD_OP  415

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPDigitMap. */
#define MDMOID_OAMSIP_DGT_MP  416

/*! \brief InternetGatewayDevice.SoftwareModules. */
#define MDMOID_SW_MODULES  417

/*! \brief InternetGatewayDevice.SoftwareModules.ExecutionUnit.{i}. */
#define MDMOID_EU  418

/*! \brief InternetGatewayDevice.SoftwareModules.ExecutionUnit.{i}.Extensions. */
#define MDMOID_EXTENSIONS  419

/*! \brief InternetGatewayDevice.SoftwareModules.ExecEnv.{i}. */
#define MDMOID_EXEC_ENV  420

/*! \brief InternetGatewayDevice.SoftwareModules.DeploymentUnit.{i}. */
#define MDMOID_DU  421

/*! \brief InternetGatewayDevice.X_404A03_WebActivityLog. */
#define MDMOID_WEB_ACTIVITY_LOG  422

/*! \brief InternetGatewayDevice.Device. */
#define MDMOID_DEVICE  423

/*! \brief InternetGatewayDevice.Device.Optical. */
#define MDMOID_DEVICE_OPTICAL  424

/*! \brief InternetGatewayDevice.Device.Optical.Interface.{i}. */
#define MDMOID_OPTICAL_INTERFACE  425

/*! \brief InternetGatewayDevice.Device.Optical.Interface.{i}.Stats. */
#define MDMOID_OPTICAL_INTERFACE_STATS  426

/*! \brief maximum OID value */
#define MDM_MAX_OID 426



#endif /* __MDM_OBJECTID_H__ */
